name: Compress images
on: push
jobs:
  build:
    name: calibreapp/image-actions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/push@master
      - name: calibre/image-actions
        uses: docker://calibre/image-actions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
