name: CI

on:
  push:
  paths:
    - '*'        # Run workflow for all file paths
    branches:
    - master
jobs:
  build:

    runs-on: ubuntu-latest
    
name: Compress images
on: push
jobs:
  build:
    name: calibreapp/image-actions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: calibreapp/image-actions
        uses: docker://calibreapp/github-image-actions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

